# Generated by Django 2.0.2 on 2018-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_imgs/default.jpg', upload_to='event_imgs'),
        ),
    ]
