# Generated by Django 2.0.2 on 2018-02-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180221_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fk_canton',
            new_name='canton',
        ),
        migrations.AlterField(
            model_name='event',
            name='fk_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Address'),
        ),
    ]
