# Generated by Django 2.0.2 on 2018-02-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180221_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='canton',
            new_name='fk_canton',
        ),
        migrations.AlterField(
            model_name='event',
            name='fk_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Address'),
        ),
    ]
