# Generated by Django 2.0.2 on 2018-02-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180225_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fk_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img'),
        ),
    ]
