# Generated by Django 2.0.2 on 2018-02-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180225_1619'),
        ('home', '0009_auto_20180225_1421'),
    ]

    operations = [
    ]
